//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confuser.CLI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Confuser.CLI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Either a single project file or the assemblies for obfuscation ähnelt.
        /// </summary>
        internal static string ArgumentFilesDescription {
            get {
                return ResourceManager.GetString("ArgumentFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ConfuserEx ähnelt.
        /// </summary>
        internal static string ConsoleTitle {
            get {
                return ResourceManager.GetString("ConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ConfuserEx - Running… ähnelt.
        /// </summary>
        internal static string ConsoleTitleRunning {
            get {
                return ResourceManager.GetString("ConsoleTitleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error loading project:
        ///{0} ähnelt.
        /// </summary>
        internal static string ErrorLoadingProjectFailed {
            get {
                return ResourceManager.GetString("ErrorLoadingProjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required output directory was not specified. ähnelt.
        /// </summary>
        internal static string ErrorNoOutputSpecified {
            get {
                return ResourceManager.GetString("ErrorNoOutputSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected error:
        ///{0} ähnelt.
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In case only one ConfuserEx project file is supplied as file, the project is used as is for the execution.
        ///In case multiple files are used, all ConfuserEx projects are used for it&apos;s rules and the other files are used as assemblies to obfuscate. ähnelt.
        /// </summary>
        internal static string ExtendedHelpText {
            get {
                return ResourceManager.GetString("ExtendedHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables the generation of debug symbols. ähnelt.
        /// </summary>
        internal static string OptionDebugDescription {
            get {
                return ResourceManager.GetString("OptionDebugDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No pause after finishing protection. ähnelt.
        /// </summary>
        internal static string OptionNoPauseDescription {
            get {
                return ResourceManager.GetString("OptionNoPauseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specifies output directory. ähnelt.
        /// </summary>
        internal static string OptionOutDirDescription {
            get {
                return ResourceManager.GetString("OptionOutDirDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specifies plugin path. ähnelt.
        /// </summary>
        internal static string OptionPluginDescription {
            get {
                return ResourceManager.GetString("OptionPluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specifies probe directory. ähnelt.
        /// </summary>
        internal static string OptionProbeDescription {
            get {
                return ResourceManager.GetString("OptionProbeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specifies the output verbosity. ähnelt.
        /// </summary>
        internal static string OptionVerbosityDescription {
            get {
                return ResourceManager.GetString("OptionVerbosityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press any key to continue… ähnelt.
        /// </summary>
        internal static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ConfuserEx - Command Line Interface - {0} ähnelt.
        /// </summary>
        internal static string VersionLong {
            get {
                return ResourceManager.GetString("VersionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ConfuserEx 2 ähnelt.
        /// </summary>
        internal static string VersionShort {
            get {
                return ResourceManager.GetString("VersionShort", resourceCulture);
            }
        }
    }
}
