using System;
using System.IO;
using System.Linq;
using dnlib.DotNet;
using Moq;
using Xunit;

namespace Confuser.Renamer.Test {
	internal static class Helpers {
		internal static ModuleDefMD LoadTestModuleDef() {
			var asmResolver = new AssemblyResolver { EnableTypeDefCache = true, FindExactMatch = true };
			asmResolver.DefaultModuleContext = new ModuleContext(asmResolver);
			var options = new ModuleCreationOptions(asmResolver.DefaultModuleContext) {
				TryToLoadPdbFromDisk = false,
			};

			asmResolver.AddToCache(ModuleDefMD.Load(typeof(Mock).Module, options));
			asmResolver.AddToCache(ModuleDefMD.Load(typeof(FactAttribute).Module, options));

#if NETCOREAPP
			asmResolver.PreSearchPaths.Add(Path.GetDirectoryName(typeof(System.Reflection.Assembly).Module.Assembly.Location));
			asmResolver.AddToCache(ModuleDefMD.Load(typeof(Microsoft.VisualStudio.TestPlatform.TestSDKAutoGeneratedCode).Module, options));
			//asmResolver.AddToCache(ModuleDefMD.Load(typeof(System.Reflection.Assembly).Module, options));
			//var addModules = AppDomain.CurrentDomain.GetAssemblies()
			//	.Where(a => !a.IsDynamic && string.Equals(a.GetName().Name, "System.Runtime", StringComparison.OrdinalIgnoreCase))
			//	.SelectMany(a => a.GetModules());
			//foreach (var mod in addModules) {
			//	asmResolver.AddToCache(ModuleDefMD.Load(mod, options));
			//}
#endif

			var thisModule = ModuleDefMD.Load(typeof(VTableTest).Module, options);
			asmResolver.AddToCache(thisModule);

			return thisModule;
		}
	}
}
